/**
 * Tactical theme styles (OLED black + Amber).
 * Used when NativeWind is disabled - expo start hangs with NativeWind on this project.
 */
import { StyleSheet } from 'react-native';

export const tactical = {
  black: '#000000',
  amber: '#FFBF00',
  zinc: {
    400: '#a1a1aa',
    500: '#71717a',
    700: '#3f3f46',
    900: '#18181b',
  },
};

export const tacticalStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: tactical.black },
  card: {
    backgroundColor: tactical.zinc[900],
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: tactical.zinc[700],
  },
  cardText: { color: '#ffffff', fontSize: 18, fontWeight: '600' },
  cardSubtext: { color: tactical.zinc[400], fontSize: 14, marginTop: 4 },
  emptyText: { color: tactical.zinc[500], padding: 24, textAlign: 'center' },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: tactical.amber,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabText: { color: tactical.black, fontSize: 28, fontWeight: '300' },
  input: {
    backgroundColor: tactical.zinc[900],
    borderWidth: 1,
    borderColor: tactical.zinc[700],
    borderRadius: 12,
    padding: 12,
    color: '#ffffff',
    marginBottom: 16,
  },
  label: { color: tactical.zinc[400], fontSize: 14, marginBottom: 4 },
  btnPrimary: {
    backgroundColor: tactical.amber,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  btnPrimaryText: { color: tactical.black, fontWeight: '700', fontSize: 18 },
  btnSmall: {
    backgroundColor: tactical.amber,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    alignSelf: 'center',
  },
  btnSmallText: { color: tactical.black, fontWeight: '600' },
  btnSecondary: {
    backgroundColor: tactical.zinc[900],
    borderWidth: 1,
    borderColor: tactical.zinc[700],
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
  },
  btnSecondaryText: { color: '#ffffff' },
  header: { padding: 16 },
  headerText: { color: tactical.zinc[400], fontSize: 14 },
  categoryChip: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 12 },
  categoryChipActive: { backgroundColor: tactical.amber },
  categoryChipInactive: { backgroundColor: tactical.zinc[900], borderWidth: 1, borderColor: tactical.zinc[700] },
  categoryChipTextActive: { color: tactical.black, fontWeight: '600' },
  categoryChipTextInactive: { color: '#ffffff' },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  rowItem: { flex: 1 },
  sectionTitle: { color: '#ffffff', fontSize: 18, fontWeight: '600', marginTop: 24, marginBottom: 8 },
  sectionDesc: { color: tactical.zinc[500], fontSize: 14, marginBottom: 8 },
  rowInline: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16 },
  inputSmall: {
    width: 80,
    backgroundColor: tactical.zinc[900],
    borderWidth: 1,
    borderColor: tactical.zinc[700],
    borderRadius: 12,
    padding: 12,
    color: '#ffffff',
    fontSize: 16,
  },
  centerScreen: {
    flex: 1,
    backgroundColor: tactical.black,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  titleAmber: { color: tactical.amber, fontSize: 24, fontWeight: '700', marginBottom: 8 },
  titleAmberSm: { color: tactical.amber, fontSize: 20, fontWeight: '700' },
  titleAmberMuted: { color: 'rgba(255, 191, 0, 0.8)', fontSize: 18, marginTop: 0 },
  subtext: { color: tactical.zinc[400], marginTop: 16, textAlign: 'center' },
  subtextZinc: { color: tactical.zinc[500], marginTop: 16, textAlign: 'center' },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 40,
    padding: 16,
    borderWidth: 1,
    borderColor: '#ef4444',
    borderRadius: 12,
  },
  logoutText: { color: '#ef4444', fontSize: 16, fontWeight: '600' },
  footer: { marginTop: 24, color: tactical.zinc[500], fontSize: 14, textAlign: 'center' },
  statusBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 16,
  },
  statusBarDigital: { backgroundColor: '#166534' },
  statusBarAnalog: { backgroundColor: 'rgba(255, 191, 0, 0.3)', borderWidth: 1, borderColor: tactical.amber },
  statusBarDistress: { backgroundColor: 'rgba(220, 38, 38, 0.4)', borderWidth: 1, borderColor: '#ef4444' },
  statusText: { color: '#ffffff', fontWeight: '600', marginLeft: 8 },
  warningLabel: {
    color: tactical.zinc[500],
    fontSize: 12,
    textAlign: 'center',
    marginTop: 16,
    fontStyle: 'italic',
  },
});
